<html>
<head>
    <title><?php echo $this->pageTitle;?></title>
    <base href="<?php echo BASE_URL;?>">

    <link rel="stylesheet" type="text/css" href="view/css/main.css">
    <link rel="stylesheet" type="text/css" href="view/css/dropzone.css"/>
    <link rel='stylesheet' id='google-font2-css'  href='//fonts.googleapis.com/css?family=Merriweather%3A300%2C400%2C700&#038;ver=2.0.0-RC2' type='text/css' media='all'/>
    <link href='http://fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="<?php echo BASE_URL?>favicon.ico" />

    <script src="view/js/jquery.js"></script>
    <script src="view/js/dropzone.js"></script>
    <script src="view/js/script.js"></script>

    <meta property="og:type"            content="website" />
    <meta property="og:url"             content="http://www.giladt.com/picabo" />
    <meta property="og:title"           content="<?php echo '' ?>" />
    <meta property="og:image"           content="" />

</head>
<body oncontextmenu="return false;">

<?php echo $this->pageContent; ?>
</body>
</html>