<html>
<head>
    <title><?php echo $this->pageTitle;?></title>
    <base href="<?php echo BASE_URL;?>">
    <link rel='stylesheet' id='google-font2-css'  href='//fonts.googleapis.com/css?family=Merriweather%3A300%2C400%2C700&#038;ver=2.0.0-RC2' type='text/css' media='all'/>
    <link href='http://fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="<?php echo BASE_URL?>favicon.ico" />

    <?php if(isset($this->css)): ?>
        <?php foreach($this->css as $src):?>
            <link rel="stylesheet" type="text/css" href="<?php echo $this->escape($src);?>">
        <?php endforeach;?>
    <?php endif;?>


    <?php if(isset($this->js)): ?>
        <?php foreach($this->js as $src):?>
            <script src="<?php echo $this->escape($src);?>"></script>
        <?php endforeach;?>
    <?php endif;?>


    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.giladt.com/picabo" />
    <meta property="og:title" content="<?php echo '' ?>" />
    <meta property="og:image"  content="" />

</head>
<body >

<?php echo $this->pageContent; ?>
</body>
</html>